MvcAuth/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcAuth.Models;
using Microsoft.AspNet.Identity;

namespace MvcAuth.Controllers
{
    public class ClienteController : Controller
    {
        Ecomerce2019Entities data = new Ecomerce2019Entities();
        // GET: Doctor
        public ActionResult Index()
        {
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");
            ViewBag.Doc = data.tb_ClienteEx.ToList();
            this.GetDefaultData();
            return View();
        }

        public ActionResult Detalle()
        {
            return View();
        }


        public ActionResult searchDistrito(string distrito = null)
        {
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");

            var lst = from doc in data.tb_ClienteEx
                      join dis in data.tb_Distrito
            on doc.idDistrito equals dis.idDistrito
                      where dis.nomDistrito.StartsWith(distrito)
                      select doc;
            return View("searchDistrito", lst.ToList());
        }

        //ADD RECENT VIEWS PRODUCT IN DB
        public void AddRecentViewProduct(int pid)
        {
            if (TempShopData.UserID > 0)
            {
                tb_VistaReciente Rv = new tb_VistaReciente();
                Rv.idCliente = TempShopData.UserID;
                Rv.idDoctor = pid;
                Rv.fecha = DateTime.Now;
                data.tb_VistaReciente.Add(Rv);
                data.SaveChanges();
            }
        }


        public ActionResult DetallesCliente(int id)
        {
            var prod = data.tb_ClienteEx.Find(id);
            var reviews = data.tb_VistaReciente.Where(x => x.idCliente == id).ToList();
            ViewBag.Reviews = reviews;
            ViewBag.TotalReviews = reviews.Count();
            ViewBag.RelatedProducts = data.tb_ClienteEx.Where(y => y.idDistrito == prod.idDistrito).ToList();
            AddRecentViewProduct(id);

            var ratedProd = data.Review.Where(x => x.IdCliente == id).ToList();
            int count = ratedProd.Count();
            int TotalRate = ratedProd.Sum(x => x.Rate).GetValueOrDefault();
            ViewBag.AvgRate = TotalRate > 0 ? TotalRate / count : 0;

            this.GetDefaultData();
            return View(prod);
        }
        
    }
}

MvcAuth/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcAuth.Models;
using Microsoft.AspNet.Identity;
using System.Web.Helpers;
using System.IO;
using System.Drawing;
using System.Drawing.Imaging;

namespace MvcAuth.Controllers
{
    public class DoctorController : Controller
    {
        Ecomerce2019Entities data = new Ecomerce2019Entities();
        int cont = 0;
        // GET: Doctor
        public ActionResult Index()
        {
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");
            ViewBag.Doc = data.tb_Doctor.ToList();
            this.GetDefaultData();
            return View();
        }

        public ActionResult Detalle()
        {
            return View();
        }

        public ActionResult findEspe(string espe = null)
        {
            // ViewBag.especialidad = data.tb_Doctor.ToList();
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");

            var query = from d in data.tb_Doctor
                        join e in data.tb_Categoria on d.idCategoria equals e.idCategoria
                        where e.nomCtegoria.StartsWith(espe)
                        select d;
            return View("findEspe", query.ToList());
        }

        public ActionResult searchEspe(int espe = 0)
        {
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria", espe);
            var lst = from d in data.tb_Doctor
                      where d.idCategoria.Equals(espe)
                      select d;
            return View("findEspe", lst.ToList());
        }

        public ActionResult searchDistrito(string distrito = null)
        {
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");

            var lst = from doc in data.tb_Doctor
                      join dis in data.tb_Distrito
            on doc.idDistrito equals dis.idDistrito
                      where dis.nomDistrito.StartsWith(distrito)
                      select doc;
            return View("searchDistrito", lst.ToList());
        }


        public ActionResult findDoctorParam(string nom = null, string dis = null, string esp = null, int pre1 = 0, int pre2 = 0)
        {
            // ViewBag.especialidad = data.tb_Doctor.ToList();
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");
            ViewBag.distrito = new SelectList(data.tb_Distrito.ToList(), "idDistrito", "nomDistrito");
            var query = from d in data.tb_Doctor
                        join e in data.tb_Categoria on d.idCategoria equals e.idCategoria
                        join f in data.tb_Distrito on d.idDistrito equals f.idDistrito

                        where e.nomCtegoria.StartsWith(esp) && f.nomDistrito.StartsWith(dis) && (d.Precio > pre1 && d.Precio < pre2)
                     || d.nomDoctor.StartsWith(nom)
                      orderby d.tb_Categoria.nomCtegoria ascending
                        select d;
            return View("findDoctorParam", query.ToList());
        }


        public ActionResult searchDoctorParam(string nom = null, int dis = 0, int esp = 0, int pre1 = 0, int pre2 = 0)
        {
            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria", esp);
            ViewBag.distrito = new SelectList(data.tb_Distrito.ToList(), "idDistrito", "nomDistrito", dis);
            var lst = from dc in data.tb_Doctor
                      join es in data.tb_Categoria
                      on dc.idCategoria equals es.idCategoria
                      join ds in data.tb_Distrito
                      on dc.idDistrito equals ds.idDistrito
                      where ds.idDistrito.Equals(dis) &&
                      es.idCategoria.Equals(esp) &&
                      (dc.Precio >= pre1 && dc.Precio <= pre2) || dc.nomDoctor == nom
                      orderby es.nomCtegoria ascending
                      select dc;
            return View("findDoctorParam", lst.ToList());
        }


        //ADD RECENT VIEWS PRODUCT IN DB
        public void AddRecentViewProduct(int pid)
        {
            if (TempShopData.UserID > 0)
            {
                tb_VistaReciente Rv = new tb_VistaReciente();
                Rv.idCliente = TempShopData.UserID;
                Rv.idDoctor = pid;
                Rv.fecha = DateTime.Now;
                data.tb_VistaReciente.Add(Rv);
                data.SaveChanges();
            }
        }


        public ActionResult DetallesDoctor(int id)
        {
            var prod = data.tb_Doctor.Find(id);
            var reviews = data.tb_VistaReciente.Where(x => x.idDoctor == id).ToList();
            ViewBag.Reviews = reviews;
            ViewBag.TotalReviews = reviews.Count();
            ViewBag.RelatedProducts = data.tb_Doctor.Where(y => y.idCategoria == prod.idCategoria).ToList();
            AddRecentViewProduct(id);

            var ratedProd = data.Review.Where(x => x.IdDoctor == id).ToList();
            int count = ratedProd.Count();
            int TotalRate = ratedProd.Sum(x => x.Rate).GetValueOrDefault();
            ViewBag.AvgRate = TotalRate > 0 ? TotalRate / count : 0;

            this.GetDefaultData();
            return View(prod);
        }


        public ActionResult WishList(int id)
        {
            //TempShopData.UsrID = User.Identity.GetUserId();
            var query = from d in data.tb_ListaDeseosExt
                        where d.idCliente.Equals(TempShopData.UsrID)
                        select d;
            var query2 = from d in data.tb_ListaDeseosExt
                        select d;
            int idx = 0;
         
          
            tb_ListaDeseosExt wl= new tb_ListaDeseosExt();
           
            foreach (var a in query)
            {
                //a.idDoctor != id
                if (a.idDoctor!=id)
                {
                    idx = 1; //aquí
                }
                else 
                {
                    idx = 0;
                    cont++;
                }
               

            }
            if (idx == 0 && cont==0)
            {
                wl = new tb_ListaDeseosExt();
                wl.idDoctor = id;
                wl.idCliente = User.Identity.GetUserId();
                data.tb_ListaDeseosExt.Add(wl);
                data.SaveChanges();
            }
            else if(idx == 1)
            {
                wl.idDoctor = id;
                wl.idCliente = User.Identity.GetUserId();
                data.tb_ListaDeseosExt.Add(wl);
                data.SaveChanges();
            }
            

            AddRecentViewProduct(id);
            ViewBag.WlItemsNo = data.tb_ListaDeseosExt.Where(x => x.idCliente == TempShopData.UsrID).ToList().Count();

            if (TempData["returnURL"].ToString() == "/")
            {
                return RedirectToAction("Index", "Home");
            }
            return Redirect(TempData["returnURL"].ToString());
        }


        public ActionResult AddToCart(int id)
        {


            int idx = 0;

            int cont = 0;
            tb_detalleOrden OD = new tb_detalleOrden();
            OD.idDoctor = id;
            int Qty = 1;
            decimal price = data.tb_Doctor.Find(id).Precio;
            OD.cantidad = 7;
            OD.precioUnidad = price;
            OD.cantidadTotal = Qty + price;
            OD.tb_Doctor = data.tb_Doctor.Find(id);

            if (TempShopData.items == null)
            {
                TempShopData.items = new List<tb_detalleOrden>();
            }

            var query = from d in TempShopData.items
                        select d;
            foreach (var a in query)
            {

                if (a.idDoctor != OD.idDoctor)
                {
                    idx = 1;

                }
                else
                {
                    idx = 0;
                    cont++;
                }

            }
            if (idx == 0 && cont == 0)
            {

                TempShopData.items.Add(OD);
                ///////////////////////////////////////////////////////////

                AddRecentViewProduct(id);

                //////////////////////////////////////////////////////////
            }
            else if (idx == 1)
            {

                TempShopData.items.Add(OD);
                ///////////////////////////////////////////////////////////

                AddRecentViewProduct(id);

                //////////////////////////////////////////////////////////
            }
            return Redirect(TempData["returnURL"].ToString());

        }



        /**************************************************REGISTRO*****************************************************/
        /***************************************************INICIO******************************************************/
        public ActionResult RegisterDoctor()
        {

            ViewBag.especialidad = new SelectList(data.tb_Categoria.ToList(), "idCategoria", "nomCtegoria");
            ViewBag.distrito = new SelectList(data.tb_Distrito.ToList(), "idDistrito", "nomDistrito");
            ViewBag.horario = new SelectList(data.tb_Horario.ToList(), "id_Horario", "dia");

            TempShopData.UsrID = User.Identity.GetUserId();
            ViewBag.user = TempShopData.UsrID;

            var query = from d in data.tb_Doctor
                        where d.idUser.Equals(TempShopData.UsrID)
                        select d;
            foreach (var a in query)
            {
                ViewBag.usr = a.idUser;
                ViewBag.doctor = a.idDoctor;
            }



            return View(new tb_Doctor());
        }

        [HttpPost]
        public ActionResult RegisterDoctor(tb_Doctor doc)
        {

MvcAuth/Views/Shared/_Cliente.cshtml
@model MvcAuth.Models.tb_ClienteEx
@using MvcAuth.Models
@using Microsoft.AspNet.Identity
<div class="item">
    <div class="team-item-2">
        <div class="team-content">
            <h4><a href="#">@Model.nomCliente  @Model.apeCliente</a></h4>
                
                
        </div>
        <div class="timetable">
            <div class="item">
                <div class="label">Distrito</div>
                <div class="value">@Model.tb_Distrito.nomDistrito</div>
            </div>
            <div class="item">
                <div class="label">Edad</div>
                <div class="value">@Model.edad</div>
            </div>
            <div class="item">
                <div class="label">Genero</div>
                <div class="value">@Model.genero</div>
            </div>


            <a class="btn-theme text-center btn-block" href="@Url.Action("DetallesCliente", "Cliente", new { id = Model.id })">
                Ver Perfil
            </a>
        </div>
   </div>
   
</div>

@{
    TempData["returnURL"] = Request.RawUrl;
}

MvcAuth/Views/Shared/_Doctor.cshtml
@model MvcAuth.Models.tb_Doctor
@using MvcAuth.Models
@using Microsoft.AspNet.Identity
<div class="item">
    <div class="team-item-2">
        <a class="aa-product-img" href="@Url.Action("DetallesDoctor", "Doctor" , new { id=Model.idDoctor })">
            @if (Model.ImageURL != null)
            {
                <img src="@Url.Content(Model.ImageURL)" width="250" height="250" alt="">
            }
            else
            {
                <img src="~/Image/descarga.jpg" width="250" height="250px;">
            }


        </a>
        <div class="team-contact">
            <ul>
                <li><a href="#"><svg class="fa fa-twitter" style="width:45px;height:45px;"><use xlink:href="#twitter" /></svg></a></li>
                <li><a href="#"><svg class="fa fa-linkedin" style="width:45px;height:45px;"><use xlink:href="#linkedin" /></svg></a></li>
                <li><a href="#"><svg class="fa fa-dribbble" style="width:45px;height:45px;"><use xlink:href="#facebook" /></svg></a></li>
            </ul>
        </div>
        <div class="team-content">
            <h4><a href="#">@Model.nomDoctor</a></h4>
            <h6>@Model.tb_Categoria.nomCtegoria</h6>
            @{

            var manager = new UserManager<ApplicationUser>
                (new Microsoft.AspNet.Identity.EntityFramework.UserStore<ApplicationUser>
                    (new ApplicationDbContext()));
                    Session["username"] = manager.FindById(User.Identity.GetUserId());
                    }
                    <a href="@(Session["username"] !=null ? Url.Action("WishList","Doctor", new { id=Model.idDoctor}) :Url.Action("Login","Account"))">
                        <svg class="team-content-icon" style="width:25px;height:25px;">
                            <use xlink:href="#like" />
                        </svg>
                    </a>
        </div>
        <div class="timetable">
            <div class="item">
                <div class="label">Lunes-Viernes</div>
                <div class="value">08:00 - 20:00</div>
            </div>
            <div class="item">
                <div class="label">Sábados</div>
                <div class="value">10:00 - 20:00</div>
            </div>
            <div class="item">
                <div class="label">Domingos</div>
                <div class="value">12:00 - 00:00</div>
            </div>
            <a class="btn-theme text-center btn-block" href="@Url.Action("DetallesDoctor", "Doctor" , new { id=Model.idDoctor })">
                Ver Perfil
            </a>

        </div>
    </div>
</div>
@{
    TempData["returnURL"] = Request.RawUrl;
}

MvcAuth/Views/Shared/_FindPartial.cshtml
@model MvcAuth.Models.tb_especialidad

MvcAuth/Views/Shared/_PartialAdmin.cshtml
@model MvcAuth.Models.tb_Doctor
@using MvcAuth.Models
@using Microsoft.AspNet.Identity




<tbody>

    <tr class="tr-shadow">
        <td>
            <label class="au-checkbox">
                <input type="checkbox">
                <span class="au-checkmark"></span>
            </label>
        </td>
        <td>@Model.nomDoctor</td>
        <td class="desc">@Model.dniDoctor</td>
        <td>
            <span class="status--process">@Model.cmpDoctor</span>
        </td>
        <td>@Model.tb_Categoria.nomCtegoria</td>

        <td>@Model.emailDoctor</td>

        <td>
            <div class="table-data-feature">
                <button class="item" data-toggle="tooltip" data-placement="top" title="Editar">

                    <a href="@Url.Action("EditarDoctor", "Admin", new { id = Model.idDoctor })">
                        <i class="flaticon-pencil-edit-button" style="left: 20%;"></i>
                    </a>
                </button>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Eliminar">
                    <a href="@Url.Action("DeleteDoctor", "Admin", new { id = Model.idDoctor })">
                        <i class="flaticon-delete" style="left: 20%;"></i>
                    </a>
                </button>
                <button class="item" data-toggle="tooltip" data-placement="top" title="Detalles">
                    <a href="@Url.Action("detalleDoctor", "Admin", new { id = Model.idDoctor })">
                        <i class="flaticon-loupe" style="left: 20%;"></i>
                    </a>
                </button>
            </div>
        </td>
    </tr>

</tbody>


@{
    TempData["returnURL"] = Request.RawUrl;
}