MvcAuth/Controllers/WishListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcAuth.Models;
using Microsoft.AspNet.Identity;

namespace MvcAuth.Controllers
{
    public class WishListController : Controller
    {
        Ecomerce2019Entities db = new Ecomerce2019Entities();
        

        // GET: WishList
        public ActionResult Index()
        {
            this.GetDefaultData();
           TempShopData.UsrID= User.Identity.GetUserId();
            var wishlistProducts = db.tb_ListaDeseosExt.Where(x => x.idCliente == TempShopData.UsrID).ToList();
            return View(wishlistProducts);
        }

        //REMOVE ITEM FROM WISHLIST
        public ActionResult Remove(int id)
        {
            db.tb_ListaDeseosExt.Remove(db.tb_ListaDeseosExt.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        //ADD TO CART WISHLIST
        public ActionResult AddToCart(int id)
        {
            int idx = 0;
            
            int cont = 0;
            tb_detalleOrden OD = new tb_detalleOrden();
            int pid = db.tb_ListaDeseosExt.Find(id).idDoctor;
            OD.idDoctor = pid;
            int Qty = 7;
            decimal price = db.tb_Doctor.Find(pid).Precio;

            OD.cantidad = 7;
            OD.precioUnidad = price;
            OD.cantidadTotal = Qty + price;
            OD.tb_Doctor = db.tb_Doctor.Find(pid);

            if (TempShopData.items == null)
            {
                TempShopData.items = new List<tb_detalleOrden>();
            }

                   var query = from d in TempShopData.items
                          select d;
                   foreach (var a in query)
                    {
         
                       if (a.idDoctor != OD.idDoctor)
                        {
                               idx = 1;

                        }
                        else
                        {
                                idx = 0;
                                cont++;
                        }

                   }
                   if (idx==0 && cont==0) {
                    
                    TempShopData.items.Add(OD);
                    ///////////////////////////////////////////////////////////
                    db.tb_ListaDeseosExt.Remove(db.tb_ListaDeseosExt.Find(id));
                    db.SaveChanges();

                    //////////////////////////////////////////////////////////
                }
                else if(idx == 1)
                {
                   
                    TempShopData.items.Add(OD);
                    ///////////////////////////////////////////////////////////
                    db.tb_ListaDeseosExt.Remove(db.tb_ListaDeseosExt.Find(id));
                    db.SaveChanges();

                    //////////////////////////////////////////////////////////

                }

            
            return Redirect(TempData["returnURL"].ToString());

        }
    }
}

MvcAuth/Views/WishList/Index.cshtml
@model IEnumerable<MvcAuth.Models.tb_ListaDeseosExt>
@{
    ViewBag.Title = "Index";
}

<section class="inner-bg over-layer-black" style="background-color:rgba(242,242,242,0.9); ">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="mini-title inner-style-2">
                    <h3>DOCTORES FAVORITOS</h3>
                    <p><a href="index-one.html">Inicio</a> <span class="fa fa-angle-right"></span> <a href="#">Doctores Favoritos</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- shopping-cart-area start -->
<div class="shoping-cart-area">
    <div class="container">
        <h4 class="mini-title inner-style-2">Tus doctores favoritos</h4>
        <div class="row">
            <div class="col-md-12">
                <div class="product-list">
                        <table style="border-color:rgba(97,157,177,0.83);">
                            <thead>
                                <tr id="new">
                                    
                                    <th>Eliminar</th>
                                    <th>Imagen</th>
                                    <th>Doctor</th>
                                    <th>Precio de visita</th>
                                    <th>Subtotal</th>
                                    <th>Total</th>
                                    <th>Solicitar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Session["username"] != null)
                                {
                                    foreach (var item in Model)
                                    {

                                            <tr>
                                                <td class="product-thumbnail">
                                                    <a href="@Url.Action("Remove", "WishList", new { id=item.idListaDeseos})"><i class="flaticon-012-mouse"></i></a>
                                                </td>
                                                <td class="product-image">
                                                    <a href="#"><img alt="" src="@item.tb_Doctor.ImageURL"></a>
                                                </td>
                                                <td>
                                                    <h4><a href="#">@item.tb_Doctor.nomDoctor</a></h4>
                                                </td>
                                                <td>@item.tb_Doctor.Precio</td>
                                                <td>@item.tb_Doctor.Precio</td>
                                                <td>@item.tb_Doctor.Precio</td>
                                                <td><a href="@Url.Action("AddToCart", "WishList", new { id=item.idListaDeseos})" class="aa-add-to-cart-btn">Solicitar Doctor</a></td>
                                            </tr>
                                            
                                    }
                                }
                                else
                                {
                                    <text>Por favor, ingrese para ver su Lista de Deseados</text>
                                }
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>